<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260929133130 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the PostgreSQL schema and the reference product categories.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'This migration targets PostgreSQL.',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE access_tokens (
              token_hash VARCHAR(64) NOT NULL,
              user_id VARCHAR(36) NOT NULL,
              expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (token_hash)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE account_tokens (
              token_hash VARCHAR(64) NOT NULL,
              user_id VARCHAR(36) NOT NULL,
              purpose VARCHAR(32) NOT NULL,
              expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              subject VARCHAR(255) DEFAULT NULL,
              consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (token_hash)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_account_tokens_user_purpose ON account_tokens (user_id, purpose)');
        $this->addSql(<<<'SQL'
            CREATE TABLE cart_items (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              product_id VARCHAR(36) NOT NULL,
              variant_id VARCHAR(36) DEFAULT NULL,
              quantity INT NOT NULL,
              position INT NOT NULL,
              cart_id VARCHAR(36) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_BEF484451AD5CDBF ON cart_items (cart_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_cart_items_cart_product_variant ON cart_items (cart_id, product_id, variant_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE carts (
              id VARCHAR(36) NOT NULL,
              customer_id VARCHAR(36) NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              version INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_carts_customer_id ON carts (customer_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE categories (
              id VARCHAR(36) NOT NULL,
              name VARCHAR(255) NOT NULL,
              slug VARCHAR(180) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_categories_slug ON categories (slug)');
        $this->addSql(<<<'SQL'
            CREATE TABLE credentials (
              user_id VARCHAR(36) NOT NULL,
              password_hash TEXT NOT NULL,
              PRIMARY KEY (user_id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE media (
              id VARCHAR(36) NOT NULL,
              owner_type VARCHAR(255) NOT NULL,
              owner_id VARCHAR(36) NOT NULL,
              filename VARCHAR(255) NOT NULL,
              relative_path VARCHAR(512) NOT NULL,
              mime_type VARCHAR(100) NOT NULL,
              size INT NOT NULL,
              position INT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_media_owner ON media (owner_type, owner_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE order_items (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              product_id VARCHAR(36) NOT NULL,
              name VARCHAR(255) NOT NULL,
              unit_price_cents INT NOT NULL,
              currency VARCHAR(3) NOT NULL,
              quantity INT NOT NULL,
              variant_id VARCHAR(36) DEFAULT NULL,
              position INT NOT NULL,
              order_id VARCHAR(36) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_62809DB08D9F6D38 ON order_items (order_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE orders (
              id VARCHAR(36) NOT NULL,
              customer_id VARCHAR(36) NOT NULL,
              status VARCHAR(32) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              shipping_recipient VARCHAR(80) DEFAULT NULL,
              shipping_line1 VARCHAR(120) DEFAULT NULL,
              shipping_line2 VARCHAR(120) DEFAULT NULL,
              shipping_postal_code VARCHAR(12) DEFAULT NULL,
              shipping_city VARCHAR(80) DEFAULT NULL,
              shipping_country VARCHAR(2) DEFAULT NULL,
              billing_recipient VARCHAR(80) DEFAULT NULL,
              billing_line1 VARCHAR(120) DEFAULT NULL,
              billing_line2 VARCHAR(120) DEFAULT NULL,
              billing_postal_code VARCHAR(12) DEFAULT NULL,
              billing_city VARCHAR(80) DEFAULT NULL,
              billing_country VARCHAR(2) DEFAULT NULL,
              shipping_method VARCHAR(20) DEFAULT NULL,
              shipping_label VARCHAR(40) DEFAULT NULL,
              shipping_fee_cents INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_orders_customer_created_at ON orders (customer_id, created_at)');
        $this->addSql(<<<'SQL'
            CREATE TABLE payments (
              id VARCHAR(36) NOT NULL,
              order_id VARCHAR(36) NOT NULL,
              customer_id VARCHAR(36) NOT NULL,
              amount_cents INT NOT NULL,
              status VARCHAR(32) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              provider VARCHAR(32) DEFAULT NULL,
              provider_reference VARCHAR(255) DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_payments_provider_reference ON payments (provider_reference)');
        $this->addSql('CREATE UNIQUE INDEX uniq_payments_order_id ON payments (order_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE product_reviews (
              id VARCHAR(36) NOT NULL,
              product_id VARCHAR(36) NOT NULL,
              author_id VARCHAR(36) NOT NULL,
              rating INT NOT NULL,
              body TEXT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_product_reviews_product_id ON product_reviews (product_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_reviews_author ON product_reviews (product_id, author_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE product_variants (
              id VARCHAR(36) NOT NULL,
              sku VARCHAR(40) NOT NULL,
              size VARCHAR(40) DEFAULT NULL,
              color VARCHAR(40) DEFAULT NULL,
              stock INT NOT NULL,
              reserved_stock INT NOT NULL,
              position INT NOT NULL,
              product_id VARCHAR(36) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_product_variants_product_id ON product_variants (product_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_variants_sku ON product_variants (sku)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_product_variants_options ON product_variants (product_id, size, color)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE products (
              id VARCHAR(36) NOT NULL,
              name VARCHAR(255) NOT NULL,
              slug VARCHAR(180) NOT NULL,
              description TEXT DEFAULT NULL,
              price_cents INT NOT NULL,
              currency VARCHAR(3) NOT NULL,
              stock INT NOT NULL,
              reserved_stock INT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              category_id VARCHAR(36) DEFAULT NULL,
              sku VARCHAR(40) NOT NULL,
              published BOOLEAN NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_products_price_cents ON products (price_cents)');
        $this->addSql('CREATE INDEX idx_products_created_at ON products (created_at)');
        $this->addSql('CREATE INDEX idx_products_name ON products (name)');
        $this->addSql('CREATE INDEX idx_products_category_id ON products (category_id)');
        $this->addSql('CREATE INDEX idx_products_published ON products (published)');
        $this->addSql('CREATE UNIQUE INDEX uniq_products_slug ON products (slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_products_sku ON products (sku)');
        $this->addSql(<<<'SQL'
            CREATE TABLE users (
              id VARCHAR(36) NOT NULL,
              email VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              role VARCHAR(32) NOT NULL,
              email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_users_email ON users (email)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cart_items
            ADD
              CONSTRAINT FK_BEF484451AD5CDBF FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              order_items
            ADD
              CONSTRAINT FK_62809DB08D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              product_variants
            ADD
              CONSTRAINT FK_782839764584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO categories (id, name, slug) VALUES
              ('11111111-1111-4111-8111-111111111111', 'T-shirts', 't-shirts'),
              ('22222222-2222-4222-8222-222222222222', 'Sweats', 'sweats'),
              ('33333333-3333-4333-8333-333333333333', 'Casquettes', 'casquettes'),
              ('44444444-4444-4444-8444-444444444444', 'Mugs', 'mugs'),
              ('55555555-5555-4555-8555-555555555555', 'Gourdes', 'gourdes'),
              ('66666666-6666-4666-8666-666666666666', 'Sacs', 'sacs'),
              ('77777777-7777-4777-8777-777777777777', 'Carnets', 'carnets'),
              ('88888888-8888-4888-8888-888888888888', 'Posters', 'posters'),
              ('99999999-9999-4999-8999-999999999999', 'Stickers', 'stickers'),
              ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', 'Chaussettes', 'chaussettes'),
              ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', 'Coques', 'coques')
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT FK_BEF484451AD5CDBF');
        $this->addSql('ALTER TABLE order_items DROP CONSTRAINT FK_62809DB08D9F6D38');
        $this->addSql('ALTER TABLE product_variants DROP CONSTRAINT FK_782839764584665A');
        $this->addSql('DROP TABLE access_tokens');
        $this->addSql('DROP TABLE account_tokens');
        $this->addSql('DROP TABLE cart_items');
        $this->addSql('DROP TABLE carts');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE credentials');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE order_items');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE product_reviews');
        $this->addSql('DROP TABLE product_variants');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE users');
    }
}
